services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/donation-app-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    image: ${DOCKERHUB_USERNAME}/donation-app-backend:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=5000
      - NODE_ENV=production
      - DB_SSL=${DB_SSL:-true}
    restart: always
